import axios from 'axios';

// Mistral AI Configuration - Updated with new API key
const MISTRAL_API_KEY = 'bnXRKcksJSDzVBl6lWYM6LVeL7XKFZ0e';
const MISTRAL_API_URL = 'https://api.mistral.ai/v1/chat/completions';

console.log('🔑 Mistral API Key configured:', MISTRAL_API_KEY ? 'Yes (' + MISTRAL_API_KEY.substring(0, 8) + '...)' : 'No');

async function generateCodeWithMistral(prompt) {
  // Input validation
  if (!prompt || !prompt.trim()) {
    throw new Error('Prompt is required and cannot be empty.');
  }

  // Validate API key
  if (!MISTRAL_API_KEY || MISTRAL_API_KEY.length < 10) {
    throw new Error('Mistral API key is not properly configured.');
  }

  try {
    console.log('🤖 Calling Mistral AI with prompt:', prompt.substring(0, 100) + '...');
    
    const requestBody = {
      model: 'mistral-large-latest',
      messages: [
        {
          role: 'system',
          content: `You are an expert full-stack developer. Generate complete, production-ready code for web applications. Always return a JSON object with a "files" array containing objects with "name", "language", and "content" properties.`
        },
        {
          role: 'user',
          content: `Create a complete web application: ${prompt}. Provide only valid JSON response.`
        }
      ],
      temperature: 0.7,
      max_tokens: 2000
    };

    console.log('📤 Sending request to Mistral API...');
    const response = await axios.post(MISTRAL_API_URL, requestBody, {
      headers: {
        'Authorization': `Bearer ${MISTRAL_API_KEY}`,
        'Content-Type': 'application/json',
      },
      timeout: 15000
    });

    console.log('✅ Received response from Mistral API');
    
    if (!response.data || !response.data.choices || !response.data.choices[0]) {
      throw new Error('Invalid response structure from Mistral API');
    }

    const content = response.data.choices[0].message.content;
    console.log('📥 Raw response length:', content.length);

    // Try to parse JSON response
    try {
      const parsed = JSON.parse(content);
      if (parsed.files && Array.isArray(parsed.files)) {
        console.log(`✅ Successfully parsed ${parsed.files.length} files`);
        return parsed.files;
      } else {
        throw new Error('Invalid files structure in response');
      }
    } catch (parseError) {
      console.log('⚠️ JSON parse failed, using fallback files');
      return createFallbackFiles(prompt);
    }
  } catch (error) {
    console.error('❌ Mistral AI API Error:', error.message);
    
    // Use fallback for any errors
    console.log('🔄 Using fallback due to API error');
    return createFallbackFiles(prompt);
  }
}

function createFallbackFiles(prompt) {
  console.log('��️ Creating fallback files for:', prompt);
  return [
    {
      name: 'index.html',
      language: 'html',
      content: `<!DOCTYPE html><html><head><title>${prompt}</title><style>body{font-family:Arial;margin:40px;background:#1a1a1a;color:white;}</style></head><body><h1>${prompt}</h1><p>Generated by Multiverse AI</p></body></html>`
    }
  ];
}

export { generateCodeWithMistral };
