const axios = require('axios');

const MISTRAL_API_KEY = '8sco68RTiZlzi3DbcmOMM8uYKiJwbOvu';
const MISTRAL_API_URL = 'https://api.mistral.ai/v1/chat/completions';

async function generateCodeWithMistral(prompt) {
  if (!prompt || !prompt.trim()) {
    throw new Error('Prompt is required and cannot be empty.');
  }

  try {
    console.log('🤖 Calling Mistral AI with prompt:', prompt.substring(0, 100) + '...');
    
    const requestBody = {
      model: 'mistral-large-latest',
      messages: [
        {
          role: 'system',
          content: 'You are an expert full-stack developer. Generate complete, production-ready code for web applications. Always return a JSON object with multiple files including frontend, backend, and documentation. Format your response as JSON with a "files" array containing objects with "name", "language", and "content" properties.'
        },
        {
          role: 'user',
          content: 'Create a complete web application: ${prompt}. Provide only valid JSON response.'
        }
      ],
      temperature: 0.7,
      max_tokens: 4000
    };

    console.log('📤 Sending request to Mistral API...');
    const response = await axios.post(MISTRAL_API_URL, requestBody, {
      headers: {
        'Authorization': 'Bearer ${MISTRAL_API_KEY}',
        'Content-Type': 'application/json',
      },
      timeout: 30000
    });

    console.log('✅ Received response from Mistral API');
    
    if (!response.data || !response.data.choices || !response.data.choices[0]) {
      throw new Error('Invalid response structure from Mistral API');
    }

    const content = response.data.choices[0].message.content;
    console.log('📥 Raw response length:', content.length);

    try {
      const parsed = JSON.parse(content);
      if (parsed.files && Array.isArray(parsed.files)) {
        console.log('✅ Successfully parsed ${parsed.files.length} files');
        return parsed.files;
      } else {
        throw new Error('Invalid files structure in response');
      }
    } catch (parseError) {
      console.log('⚠️ JSON parse failed, using fallback files');
      return createFallbackFiles(prompt);
    }
  } catch (error) {
    console.error('❌ Mistral AI API Error:', error.response?.data || error.message);
    
    if (error.code === 'ECONNREFUSED' || error.message.includes('ENOTFOUND')) {
      throw new Error('Cannot connect to Mistral AI service. Check your internet connection.');
    } else if (error.response?.status === 401) {
      throw new Error('Invalid Mistral AI API key.');
    } else if (error.response?.status === 429) {
      throw new Error('Mistral AI rate limit exceeded. Please try again in a moment.');
    } else if (error.response?.status === 503) {
      throw new Error('Mistral AI service is temporarily unavailable.');
    } else if (error.message.includes('timeout')) {
      throw new Error('Mistral AI request timed out. Please try again.');
    } else {
      throw new Error('Mistral AI generation failed: ${error.message}');
    }
  }
}

function createFallbackFiles(prompt) {
  console.log('🛠️ Creating fallback files for prompt:', prompt);
  return [
    {
      name: 'index.html',
      language: 'html',
      content: '<!DOCTYPE html><html><head><title>${prompt}</title><style>body{font-family:Arial;margin:40px;background:#1a1a1a;color:white;}</style></head><body><h1>${prompt}</h1><p>Generated by Multiverse AI</p></body></html>'
    },
    {
      name: 'styles.css',
      language: 'css',
      content: 'body { font-family: Arial, sans-serif; margin: 40px; background: #1a1a1a; color: white; }'
    },
    {
      name: 'script.js', 
      language: 'javascript',
      content: 'console.log("${prompt} application loaded");'
    }
  ];
}

module.exports = { generateCodeWithMistral };
