import React, { useState, useRef, useEffect } from 'react';
import { MultiverseAIService } from '../lib/llm/mistralService';
import { useSpeechToText } from '../hooks/useSpeechToText';
import { GitHubService } from '../lib/github/githubService';

interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  model?: string;
  isCode?: boolean;
}

export default function BaseChat() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [selectedModels, setSelectedModels] = useState<string[]>(['nebula-mistral']);
  const [generatedCode, setGeneratedCode] = useState<string>('');
  const [githubToken, setGithubToken] = useState('');
  
  const aiServiceRef = useRef(new MultiverseAIService());
  const { isListening, transcript, isSupported, startListening, stopListening } = useSpeechToText();

  useEffect(() => {
    setInput(transcript);
  }, [transcript]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isGenerating) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      role: 'user',
      content: input
    };

    setMessages(prev => [...prev, userMessage]);
    setInput('');
    setIsGenerating(true);

    const responses = new Map<string, string>();

    try {
      await aiServiceRef.current.generateWithAllModels(
        [...messages, userMessage].map(m => ({ role: m.role, content: m.content })),
        (model, chunk) => {
          const currentContent = responses.get(model) || '';
          const newContent = currentContent + chunk;
          responses.set(model, newContent);
          
          setMessages(prev => {
            const newMessages = [...prev];
            const existingAssistantMsgIndex = newMessages.findIndex(
              m => m.role === 'assistant' && m.model === model
            );

            if (existingAssistantMsgIndex !== -1) {
              newMessages[existingAssistantMsgIndex].content = newContent;
            } else {
              newMessages.push({
                id: `${model}-${Date.now()}`,
                role: 'assistant',
                model,
                content: newContent,
                isCode: newContent.includes('```') || newContent.includes('function') || newContent.includes('const ')
              });
            }

            return newMessages;
          });
        }
      );

      let allCode = '';
      responses.forEach((content, model) => {
        allCode += `// Generated by ${model}\n${content}\n\n`;
      });
      setGeneratedCode(allCode);

    } catch (error) {
      console.error('Generation error:', error);
      setMessages(prev => [...prev, {
        id: 'error',
        role: 'assistant',
        content: 'Sorry, there was an error generating the response. Please try again.',
        model: 'system'
      }]);
    } finally {
      setIsGenerating(false);
    }
  };

  const speakText = (text: string) => {
    if (typeof window !== 'undefined' && (window as any).responsiveVoice) {
      (window as any).responsiveVoice.speak(text, 'UK English Female', {
        rate: 0.9,
        pitch: 1,
        volume: 1
      });
    }
  };

  const deployToGitHub = async () => {
    if (!githubToken) {
      alert('Please enter your GitHub personal access token');
      return;
    }

    if (!generatedCode) {
      alert('No code generated yet');
      return;
    }

    try {
      const githubService = new GitHubService(githubToken);
      const files = [
        {
          path: 'index.html',
          content: `<!DOCTYPE html>
<html>
<head>
    <title>Multiverse Generated App</title>
    <style>body { font-family: Arial, sans-serif; margin: 40px; }</style>
</head>
<body>
    <h1>Welcome to Your Multiverse App</h1>
    <div id="app">${generatedCode}</div>
    <div class="multiverse-edit">
        <a href="https://your-multiverse-domain.com" target="_blank">Edit with Multiverse</a>
    </div>
</body>
</html>`
        },
        {
          path: 'README.md',
          content: `# Multiverse Generated App\n\nThis app was generated using Multiverse AI Builder.`
        }
      ];

      const result = await githubService.createProjectFromCode(
        files,
        `multiverse-app-${Date.now()}`,
        'Web app generated by Multiverse AI Builder'
      );

      alert(`Successfully deployed to GitHub!\nRepository: ${result.repoUrl}\nLive Site: ${result.pagesUrl}`);
    } catch (error) {
      console.error('GitHub deployment failed:', error);
      alert('Failed to deploy to GitHub. Please check your token and try again.');
    }
  };

  return (
    <div className="chat-container">
      <div className="models-selector">
        <h3>🚀 Galaxian Models</h3>
        <div className="model-toggles">
          {Object.entries(aiServiceRef.current.models.free).map(([id, name]) => (
            <label key={id} className="model-toggle">
              <input
                type="checkbox"
                checked={selectedModels.includes(id)}
                onChange={(e) => {
                  if (e.target.checked) {
                    setSelectedModels(prev => [...prev, id]);
                  } else {
                    setSelectedModels(prev => prev.filter(m => m !== id));
                  }
                }}
              />
              {id} (Free)
            </label>
          ))}
          {Object.entries(aiServiceRef.current.models.premium).map(([id, name]) => (
            <label key={id} className="model-toggle premium">
              <input
                type="checkbox"
                checked={selectedModels.includes(id)}
                onChange={(e) => {
                  if (e.target.checked) {
                    setSelectedModels(prev => [...prev, id]);
                  } else {
                    setSelectedModels(prev => prev.filter(m => m !== id));
                  }
                }}
              />
              {id} ⭐
            </label>
          ))}
        </div>
      </div>

      <div className="messages-container">
        {messages.map(message => (
          <div key={message.id} className={`message ${message.role} ${message.isCode ? 'code-message' : ''}`}>
            <strong>{message.role === 'assistant' ? `🤖 ${message.model}` : '👤 You'}:</strong>
            <pre>{message.content}</pre>
            {message.role === 'assistant' && (
              <button onClick={() => speakText(message.content)} className="speak-btn">
                🔊 Speak
              </button>
            )}
          </div>
        ))}
      </div>

      {generatedCode && (
        <div className="deployment-section">
          <h4>🚀 Deployment Options</h4>
          <div className="github-deploy">
            <input
              type="password"
              placeholder="GitHub Personal Access Token"
              value={githubToken}
              onChange={(e) => setGithubToken(e.target.value)}
              className="token-input"
            />
            <button onClick={deployToGitHub} className="deploy-btn">
              Deploy to GitHub Pages
            </button>
          </div>
        </div>
      )}

      <form onSubmit={handleSubmit} className="input-form">
        <div className="input-container">
          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Describe your web app or use voice input..."
            rows={3}
            disabled={isGenerating}
          />
          
          <div className="voice-controls">
            {isSupported ? (
              <button
                type="button"
                onClick={isListening ? stopListening : startListening}
                className={`voice-btn ${isListening ? 'listening' : ''}`}
              >
                {isListening ? '🛑 Stop' : '🎤 Speak'}
              </button>
            ) : (
              <span className="voice-unsupported">🎤 Not Supported</span>
            )}
          </div>
        </div>

        <button 
          type="submit"
          disabled={!input.trim() || isGenerating}
          className="send-button"
        >
          {isGenerating ? '🚀 Generating...' : 'Send to All Models'}
        </button>
      </form>
    </div>
  );
}
