import React, { useState, useRef, useEffect } from 'react';
import { MultiverseAIService } from '../lib/llm/mistralService';
import { useSpeechToText } from '../hooks/useSpeechToText';
import { GitHubService } from '../lib/github/githubService';
import './BaseChat.css';

interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  model?: string;
  isCode?: boolean;
  timestamp: Date;
}

interface BaseChatProps {
  onCodeGenerated: (code: string) => void;
}

export default function BaseChat({ onCodeGenerated }: BaseChatProps) {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [selectedModels, setSelectedModels] = useState<string[]>(['nebula-mistral']);
  const [githubToken, setGithubToken] = useState('');
  const [showDeploy, setShowDeploy] = useState(false);
  
  const aiServiceRef = useRef(new MultiverseAIService());
  const { isListening, transcript, isSupported, startListening, stopListening } = useSpeechToText();
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    setInput(transcript);
  }, [transcript]);

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isGenerating) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      role: 'user',
      content: input,
      timestamp: new Date()
    };

    setMessages(prev => [...prev, userMessage]);
    setInput('');
    setIsGenerating(true);
    setShowDeploy(false);

    const responses = new Map<string, string>();

    try {
      await aiServiceRef.current.generateWithAllModels(
        [...messages, userMessage].map(m => ({ role: m.role, content: m.content })),
        (model, chunk) => {
          const currentContent = responses.get(model) || '';
          const newContent = currentContent + chunk;
          responses.set(model, newContent);
          
          setMessages(prev => {
            const newMessages = [...prev];
            const existingAssistantMsgIndex = newMessages.findIndex(
              m => m.role === 'assistant' && m.model === model
            );

            if (existingAssistantMsgIndex !== -1) {
              newMessages[existingAssistantMsgIndex].content = newContent;
            } else {
              newMessages.push({
                id: `${model}-${Date.now()}`,
                role: 'assistant',
                model,
                content: newContent,
                isCode: newContent.includes('```') || newContent.includes('function') || newContent.includes('const ') || newContent.includes('<'),
                timestamp: new Date()
              });
            }

            return newMessages;
          });
        }
      );

      // Collect all generated code
      let allCode = '';
      responses.forEach((content, model) => {
        allCode += `// Generated by ${model}\n${content}\n\n`;
      });
      
      onCodeGenerated(allCode);
      setShowDeploy(true);

    } catch (error) {
      console.error('Generation error:', error);
      setMessages(prev => [...prev, {
        id: 'error',
        role: 'assistant',
        content: 'Sorry, there was an error generating the response. Please check your API keys and try again.',
        model: 'system',
        timestamp: new Date()
      }]);
    } finally {
      setIsGenerating(false);
    }
  };

  const deployToGitHub = async () => {
    if (!githubToken) {
      alert('Please enter your GitHub personal access token');
      return;
    }

    const latestCode = messages
      .filter(m => m.role === 'assistant' && m.isCode)
      .slice(-1)[0]?.content;

    if (!latestCode) {
      alert('No code generated yet');
      return;
    }

    try {
      const githubService = new GitHubService(githubToken);
      const result = await githubService.createProjectFromCode(
        [{ path: 'index.html', content: latestCode }],
        `multiverse-app-${Date.now()}`,
        'Web app generated by Multiverse AI Builder'
      );

      alert(`🎉 Successfully deployed to GitHub!\n\n📁 Repository: ${result.repoUrl}\n🌐 Live Site: ${result.pagesUrl}`);
    } catch (error) {
      console.error('GitHub deployment failed:', error);
      alert('❌ Failed to deploy to GitHub. Please check your token and try again.');
    }
  };

  const formatTime = (date: Date) => {
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  };

  return (
    <div className="base-chat">
      <div className="chat-header">
        <h3>🚀 AI Models</h3>
        <p>Select models to generate code simultaneously</p>
      </div>

      <div className="models-grid">
        {Object.entries(aiServiceRef.current.models.free).map(([id, name]) => (
          <label key={id} className="model-card free">
            <input
              type="checkbox"
              checked={selectedModels.includes(id)}
              onChange={(e) => {
                if (e.target.checked) {
                  setSelectedModels(prev => [...prev, id]);
                } else {
                  setSelectedModels(prev => prev.filter(m => m !== id));
                }
              }}
            />
            <div className="model-info">
              <span className="model-name">{id}</span>
              <span className="model-status">Free</span>
            </div>
          </label>
        ))}
      </div>

      <div className="messages-container">
        {messages.map(message => (
          <div key={message.id} className={`message ${message.role}`}>
            <div className="message-header">
              <span className="message-sender">
                {message.role === 'assistant' ? `🤖 ${message.model}` : '👤 You'}
              </span>
              <span className="message-time">{formatTime(message.timestamp)}</span>
            </div>
            <div className="message-content">
              {message.content}
            </div>
          </div>
        ))}
        <div ref={messagesEndRef} />
      </div>

      {showDeploy && (
        <div className="deployment-section">
          <h4>🚀 Ready to Deploy</h4>
          <div className="github-deploy">
            <input
              type="password"
              placeholder="GitHub Personal Access Token"
              value={githubToken}
              onChange={(e) => setGithubToken(e.target.value)}
              className="token-input"
            />
            <button onClick={deployToGitHub} className="deploy-btn">
              Deploy to GitHub Pages
            </button>
          </div>
        </div>
      )}

      <form onSubmit={handleSubmit} className="input-form">
        <div className="input-container">
          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Describe your web app... (e.g., 'Create a weather dashboard with dark mode')"
            rows={3}
            disabled={isGenerating}
            className="chat-input"
          />
          
          <div className="input-controls">
            <button 
              type="submit"
              disabled={!input.trim() || isGenerating}
              className="send-button"
            >
              {isGenerating ? 'Generating...' : 'Send to All Models'}
            </button>
          </div>
        </div>
      </form>
    </div>
  );
}
