import React, { useState } from 'react';
import './App.css';

// Simple placeholder components for now
const BaseChat = ({ onCodeGenerated }: any) => {
  const [input, setInput] = useState('');
  const [messages, setMessages] = useState<Array<{id: string, role: string, content: string}>>([]);
  const [isGenerating, setIsGenerating] = useState(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim()) return;

    const userMessage = { id: Date.now().toString(), role: 'user', content: input };
    setMessages(prev => [...prev, userMessage]);
    setInput('');
    setIsGenerating(true);

    // Simulate AI response
    setTimeout(() => {
      const code = `<div class="app">
  <header style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 2rem; color: white; text-align: center;">
    <h1>Your ${input} App</h1>
    <p>Generated by Multiverse AI</p>
  </header>
  <main style="padding: 2rem; max-width: 1200px; margin: 0 auto;">
    <div style="background: white; padding: 2rem; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.1);">
      <h2>Welcome to Your App</h2>
      <p>This is a fully functional web app generated based on your description: "${input}"</p>
      <button style="background: #667eea; color: white; border: none; padding: 1rem 2rem; border-radius: 8px; cursor: pointer; margin-top: 1rem;">
        Get Started
      </button>
    </div>
  </main>
</div>`;
      
      const assistantMessage = { 
        id: (Date.now() + 1).toString(), 
        role: 'assistant', 
        content: `I've generated a complete web app for: "${input}"\n\nHere's the HTML code:\n\n${code}` 
      };
      
      setMessages(prev => [...prev, assistantMessage]);
      onCodeGenerated(code);
      setIsGenerating(false);
    }, 2000);
  };

  return (
    <div style={{ 
      height: '100%', 
      display: 'flex', 
      flexDirection: 'column',
      background: 'white',
      borderRadius: '12px',
      overflow: 'hidden'
    }}>
      <div style={{
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        color: 'white',
        padding: '1.5rem',
        borderBottom: '1px solid #e2e8f0'
      }}>
        <h3 style={{ margin: 0, marginBottom: '0.5rem' }}>🚀 Multiverse AI Builder</h3>
        <p style={{ margin: 0, opacity: 0.9 }}>Describe any web app and get instant code</p>
      </div>

      <div style={{
        flex: 1,
        padding: '1.5rem',
        overflowY: 'auto',
        background: '#f8fafc'
      }}>
        {messages.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '2rem', color: '#64748b' }}>
            <h4 style={{ color: '#334155', marginBottom: '1rem' }}>🎉 Welcome to Multiverse AI!</h4>
            <p>Try these examples:</p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', maxWidth: '400px', margin: '0 auto' }}>
              {[
                "Create a weather dashboard with dark mode",
                "Build a task management app", 
                "Make a portfolio website"
              ].map((prompt, i) => (
                <div 
                  key={i}
                  onClick={() => setInput(prompt)}
                  style={{
                    background: 'white',
                    padding: '1rem',
                    borderRadius: '8px',
                    border: '1px solid #e2e8f0',
                    cursor: 'pointer',
                    transition: 'all 0.2s ease'
                  }}
                  onMouseOver={(e) => e.currentTarget.style.borderColor = '#667eea'}
                  onMouseOut={(e) => e.currentTarget.style.borderColor = '#e2e8f0'}
                >
                  {prompt}
                </div>
              ))}
            </div>
          </div>
        ) : (
          messages.map(msg => (
            <div key={msg.id} style={{
              padding: '1rem',
              borderRadius: '12px',
              marginBottom: '1rem',
              maxWidth: '80%',
              alignSelf: msg.role === 'user' ? 'flex-end' : 'flex-start',
              marginLeft: msg.role === 'user' ? 'auto' : '0',
              background: msg.role === 'user' 
                ? 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)' 
                : 'white',
              color: msg.role === 'user' ? 'white' : 'inherit',
              border: msg.role === 'assistant' ? '1px solid #e2e8f0' : 'none'
            }}>
              <div style={{ whiteSpace: 'pre-wrap', lineHeight: '1.5' }}>
                {msg.content}
              </div>
            </div>
          ))
        )}
        {isGenerating && (
          <div style={{
            padding: '1rem',
            borderRadius: '12px',
            background: 'white',
            border: '1px solid #e2e8f0',
            maxWidth: '80%'
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: '#64748b' }}>
              <div style={{
                width: '16px',
                height: '16px',
                border: '2px solid #e2e8f0',
                borderTop: '2px solid #667eea',
                borderRadius: '50%',
                animation: 'spin 1s linear infinite'
              }}></div>
              AI is generating your code...
            </div>
          </div>
        )}
      </div>

      <form onSubmit={handleSubmit} style={{
        padding: '1.5rem',
        borderTop: '1px solid #e2e8f0',
        background: 'white'
      }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Describe your web app... (e.g., 'Create a modern dashboard with dark mode')"
            rows={3}
            style={{
              width: '100%',
              padding: '1rem',
              border: '2px solid #e2e8f0',
              borderRadius: '8px',
              resize: 'vertical',
              fontFamily: 'inherit',
              fontSize: '1rem'
            }}
          />
          <button 
            type="submit"
            disabled={!input.trim() || isGenerating}
            style={{
              background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
              color: 'white',
              border: 'none',
              padding: '1rem 2rem',
              borderRadius: '8px',
              cursor: 'pointer',
              fontWeight: '600',
              fontSize: '1rem',
              opacity: (!input.trim() || isGenerating) ? 0.6 : 1
            }}
          >
            {isGenerating ? '🔄 Generating...' : '🚀 Generate Code'}
          </button>
        </div>
      </form>

      <style>{`
        @keyframes spin {
          0% { transform: rotate(0deg); }
          100% { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  );
};

const CodePreview = ({ code, view }: any) => {
  if (view === 'code') {
    return (
      <div style={{ 
        height: '100%', 
        display: 'flex', 
        flexDirection: 'column',
        background: 'white',
        borderRadius: '12px',
        overflow: 'hidden'
      }}>
        <div style={{
          padding: '1rem 1.5rem',
          borderBottom: '1px solid #e2e8f0',
          background: 'linear-gradient(135deg, #2c3e50 0%, #3498db 100%)',
          color: 'white',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center'
        }}>
          <span style={{ fontWeight: '600' }}>Generated Code</span>
          <button 
            onClick={() => navigator.clipboard.writeText(code)}
            disabled={!code}
            style={{
              background: 'rgba(255,255,255,0.2)',
              color: 'white',
              border: '1px solid rgba(255,255,255,0.3)',
              padding: '0.5rem 1rem',
              borderRadius: '6px',
              cursor: 'pointer'
            }}
          >
            📋 Copy
          </button>
        </div>
        <pre style={{
          flex: 1,
          padding: '1.5rem',
          background: '#1a1a1a',
          color: '#00ff00',
          margin: 0,
          overflow: 'auto',
          fontSize: '0.9rem',
          lineHeight: '1.5'
        }}>
          {code || '// Code will appear here after generation...'}
        </pre>
      </div>
    );
  }

  return (
    <div style={{ 
      height: '100%', 
      background: 'white',
      borderRadius: '12px',
      overflow: 'hidden'
    }}>
      <div style={{
        padding: '1rem 1.5rem',
        borderBottom: '1px solid #e2e8f0',
        background: 'linear-gradient(135deg, #2c3e50 0%, #3498db 100%)',
        color: 'white'
      }}>
        <span style={{ fontWeight: '600' }}>Live Preview</span>
      </div>
      <iframe
        srcDoc={code ? `<!DOCTYPE html><html><head><title>Preview</title><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body>${code}</body></html>` : ''}
        style={{
          width: '100%',
          height: '100%',
          border: 'none',
          background: 'white'
        }}
      />
    </div>
  );
};

function App() {
  const [currentView, setCurrentView] = useState<'code' | 'preview'>('code');
  const [generatedCode, setGeneratedCode] = useState<string>('');

  return (
    <div className="app">
      <header className="app-header">
        <div className="header-content">
          <div className="logo-section">
            <h1>🚀 Multiverse AI</h1>
            <p>Build web apps with AI power</p>
          </div>
          <div className="user-section">
            <span className="user-email">Welcome, Developer!</span>
            <button className="logout-btn">
              Sign In
            </button>
          </div>
        </div>
      </header>

      <main className="app-main">
        <div className="main-container">
          <div className="chat-panel">
            <BaseChat onCodeGenerated={setGeneratedCode} />
          </div>

          <div className="preview-panel">
            <div className="panel-header">
              <div className="view-toggles">
                <button 
                  className={`toggle-btn ${currentView === 'code' ? 'active' : ''}`}
                  onClick={() => setCurrentView('code')}
                >
                  💻 Code
                </button>
                <button 
                  className={`toggle-btn ${currentView === 'preview' ? 'active' : ''}`}
                  onClick={() => setCurrentView('preview')}
                >
                  ��️ Preview
                </button>
                <button 
                  className="new-tab-btn"
                  onClick={() => {
                    if (generatedCode) {
                      const newWindow = window.open();
                      if (newWindow) {
                        newWindow.document.write(`
                          <!DOCTYPE html>
                          <html>
                          <head>
                            <title>Multiverse Preview</title>
                            <meta name="viewport" content="width=device-width, initial-scale=1.0">
                            <style>
                              body { 
                                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                                margin: 0;
                                padding: 0;
                              }
                            </style>
                          </head>
                          <body>${generatedCode}</body>
                          </html>
                        `);
                      }
                    }
                  }}
                >
                  ↗ New Tab
                </button>
              </div>
            </div>
            <div className="panel-content">
              <CodePreview code={generatedCode} view={currentView} />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

export default App;
